create table book(
    id bigint generated by default as identity primary key,
    title varchar(50) not null,
    author varchar(100) not null,
    genre varchar(50) not null,
    year_release integer check(year_release >= 1500 and year_release <= 2026)
);