spring.application.name=BookDeleteMicroservice
server.port=8082

spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.consumer.group-id=book-delete-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer


# в проде всё закинуть в .env
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/petproj
spring.datasource.username=postgres
spring.datasource.password=postgres
